FROM debian:latest

MAINTAINER Olof Hagsand <olof@hagsand.se>

ENV DEBIAN_FRONTEND noninteractive

# Packages needed for building
RUN apt-get update && apt-get install -y \
    curl \
    git \
    make \
    gcc \
    automake \
    flex \
    bison \
    libcurl4-openssl-dev

# Create a directory to hold source-code, dependencies etc
RUN mkdir /grideye
WORKDIR /grideye

# Clone all dependencies and grideye-agent
git clone https://github.com/olofhagsand/cligen.git
git clone https://github.com/clicon/clixon.git
git clone https://github.com/cloudmon360/grideye_agent.git
cd ./cligen
./configure
make
make install

cd ../clixon
./configure --without-restconf --without-keyvalue
make
make install
make install-include

cd ../grideye_agent
./configure
make
make install

cd plugins/
make install

RUN ldconfig

# Create a file for disk IO tests
RUN /bin/dd if=/dev/zero of=/var/tmp/GRIDEYE_LARGEFILE bs=1M count=1K

# Run grideye-agent
CMD grideye_agent -u $GRIDEYE_URL -I $GRIDEYE_UUID -N $GRIDEYE_NAME -F -p udp :7878 

EXPOSE 7878 7878/udp





